#!/usr/bin/env bash

# Aborts the script when the first error is detected.
set -o errexit
# Aborts the script when the first undefined variable is detected.
set -o nounset
# Allow for ERR trap inheritance through shell functions.
set -o errtrace

trap 'error_handler ${BASH_SOURCE} ${LINENO}' ERR

# Unicode characters for visual representation in the terminal
# White Heavy Check Mark (Unicode: U+2705)
OK=✅
# Check Mark (Unicode: U+2713)
YUP=✓
# High Voltage Sign as warning mark (Unicode: U+26A1)
WRN=⚡
# Cross Mark (Unicode: U+274C)
ERR=❌

error_handler() {
  local src="$1"
  local line="$2"

  echo "${ERR} Error: in ${src} at line ${line}" >&2
}

remove_tmp_file() {
  local file_to_remove="$1"

  if [[ -f "$file_to_remove" ]]; then
    rm -f "${file_to_remove}"
    echo "${YUP} Temporary file '${file_to_remove}' has been deleted"
   fi
}

check_if_gh_has_required_token_scopes() {
  # Aborts the script when the first error is detected.
  set -o errexit

  local -a token_scopes
  local -a missing_scopes

  # Fetch the current token scopes using 'gh', extract line with 'grep' and use
  # 'sed' to parse the line
  token_scopes=$(gh auth status | grep 'Token scopes' | sed 's/.*Token scopes: //')

  # Check for each required scope
  for scope in "${GH_CLI_TOKEN_SCOPES[@]}"; do
    if [[ "${token_scopes}" != *"${scope}"* ]]; then
      missing_scopes+=("${scope}")
    fi
  done

  # Inform the user about the status
  if [[ "${#missing_scopes[@]}" -ne 0 ]]; then
    echo "${ERR} Missing required token scopes:" >&2
    for scope in "${missing_scopes[@]}"; do
      echo "- ${scope}" >&2
    done
    exit 1
  fi
}

check_if_source_repos_exist() {
  # Aborts the script when the first error is detected.
  set -o errexit
  # Initialize a flag to track if any repository does not exist
  local repo_noexists_flag=0

  for ((i=0; i<"${#SOURCE_REPOS[@]}"; i++)); do
    # Check if the repository exists
    if gh repo view "${SOURCE_REPOS_OWNER}/${SOURCE_REPOS[i]}" &> /dev/null; then
      echo -n "${YUP} Repository ${SOURCE_REPOS_OWNER}/${SOURCE_REPOS[i]} "
      echo "exists as expected."
    else
      echo -n "${ERR} Repository ${SOURCE_REPOS_OWNER}/${SOURCE_REPOS[i]} " >&2
      echo "no exists." >&2
      repo_noexists_flag=1
    fi
  done

  # Check the flag and exit with an error if any repository does not exist
  if [[ "${repo_noexists_flag}" -eq 1 ]]; then
    echo -n "${ERR} For proper functioning, it is required that " >&2
    echo -n "the repositories listed in the 'SOURCE_REPOS' array " >&2
    echo -n "in the 'source_config.sh' file exist " >&2
    echo "on the '${SOURCE_REPOS_OWNER}' account." >&2
    exit 1
  else
    echo "${OK} Checking – if the source repositories exist – has been completed."
  fi
}

check_if_target_repos_noexist() {
  # Aborts the script when the first error is detected.
  set -o errexit
  # Initialize a flag to track if any repository already exists
  local repo_exists_flag=0

  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do
    # Check if the repository exists
    if ! gh repo view "${GH_ORG_NAME}/${TARGET_REPOS[i]}" &> /dev/null; then
      echo -n "${YUP} Repository ${GH_ORG_NAME}/${TARGET_REPOS[i]} "
      echo "not yet exists as expected."
    else
      echo -n "${ERR} Repository ${GH_ORG_NAME}/${TARGET_REPOS[i]} " >&2
      echo "already exists." >&2
      repo_exists_flag=1
    fi
  done

  # Check the flag and exit with an error if any repository already exists
  if [[ "${repo_exists_flag}" -eq 1 ]]; then
    echo -n "${ERR} For proper functioning, it is required that " >&2
    echo -n "the repositories listed in the 'TARGET_REPOS' array " >&2
    echo -n "in the 'user_config.sh' file do not exist " >&2
    echo "on the '${GH_ORG_NAME}' account." >&2
    exit 1
  else
    echo -n "${OK} Checking – if the target repositories not yet exist – "
    echo "has been completed."
  fi
}

fork_repositories() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  for ((i=0; i<"${#SOURCE_REPOS[@]}"; i++)); do

    # Fork the repository to the organization without cloning it locally.
    gh repo fork "${SOURCE_REPOS_OWNER}"/"${SOURCE_REPOS[i]}" \
       --org "${GH_ORG_NAME}" \
       --fork-name "${TARGET_REPOS[i]}" \
       --clone=false

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while forking the " >&2
      echo -n "${SOURCE_REPOS_OWNER}/${SOURCE_REPOS[i]} repository to " >&2
      echo "${GH_ORG_NAME}/${TARGET_REPOS[i]}" >&2
      exit 1
    fi
  done
  echo "${OK} Forking repositories has been completed"
}

set_repo_as_private_template() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do

    gh repo edit "$GH_ORG_NAME"/"${TARGET_REPOS[i]}" \
       --visibility private \
       --template=true

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while setting the " >&2
      echo "$GH_ORG_NAME/${TARGET_REPOS[i]} repository as a private template" >&2
      exit 1
    fi
  done
  echo "${OK} Setting repositories as private templates has been completed"
}

swich_on_gh_pages() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # echo "{\"source\":{\"branch\":\""${GH_REPO_BRANCH}"\",\"path\":\"/\"}}"
  echo '{"source":{"branch":"'"${GH_REPO_BRANCH}"'","path":"/"}}' | gh api \
                        --method POST \
                        --header "Accept: ${GH_API_ACCEPT_HEADER}" \
                        --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
                        /repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[0]}"/pages \
			--silent \
                        --input -

  if [[ $? -eq 0 ]]; then
    echo -n "${OK} GitHub Pages has been enabled on the '${GH_REPO_BRANCH}' "
    echo "branch in the ${GH_ORG_NAME}/${TARGET_REPOS[0]} repository."
    echo -n "${WRN} Please be patient: the creation process for the GitHub "
    echo -n "page has started, but the page itself will be available "
    echo "in about 3 minutes."
  else
    echo -n "${ERR} An error occurred while enabling the '${GH_REPO_BRANCH}' " >&2
    echo "branch in the ${GH_ORG_NAME}/${TARGET_REPOS[0]}" >&2
    exit 1
  fi
}

set_repos_website() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through repositories
  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do

    # Setting website link in the target repositories"
    gh repo edit "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}" \
       --homepage https://"${GH_ORG_NAME}".github.io/"${TARGET_REPOS[0]}"/

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while setting a website link in the " >&2
      echo "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}} repository" >&2
      exit 1
    fi
  done
  echo "$OK Setting the website links has been completed"
}

set_repos_descriptions() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through repositories
  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do

    # Setting website link in the target repositories"
    gh repo edit "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}" \
       --description "${TARGET_REPO_DESCRIPTION}"

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while setting a website link in the " >&2
      echo "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}} repository" >&2
      exit 1
    fi
  done
  echo "$OK Setting the website links has been completed"
}

get_file_sha() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Check if the correct number of non-empty arguments is passed
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    echo "${ERR} Invalid number of arguments or empty argument." >&2
    echo "${WRN} Usage: ${FUNCNAME[0]} <source_file>"
    exit 1
  fi

  # Local variable declaration for the return value
  local sha

  # Get the file SHA
  sha=$(gh api \
           --method GET \
           --header "Accept: ${GH_API_ACCEPT_HEADER}" \
           --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
           repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[0]}"/contents/"${source_file}" \
           --jq '.sha')

  if [[ $? -eq 0 ]]; then
    if [[ -n "${sha}" ]]; then
      echo "${sha}"
    else
      echo "${ERR} SHA for the '${source_file}' is emapty"
      exit 1
    fi
  else
    echo "${ERR} An error occurred while obtaining SHA for the '${source_file}'"
    exit 1
  fi
}

download_repo_file_contents_to_tmp_file() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Check if the correct number of non-empty arguments is passed
  if [[ "$#" -ne 2 || -z "$1" || -z "$2" ]]; then
    echo "${ERR} Invalid number of arguments or empty argument." >&2
    echo "${WRN} Usage: ${FUNCNAME[0]} <source_file> <temporary_file>"
    exit 1
  fi

  local source_file="$1"
  local tmp_file="$2"

  gh api \
     --method GET \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[0]}"/contents/"${source_file}" \
     --jq '.content' | base64 --decode > "${tmp_file}"

  # Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} The content of the '${source_file}' has been written "
    echo "to the '${tmp_file}'"
  else
    echo -n "${ERR} An error occurred while downloading '${source_file}' " >&2
    echo "or writing its content to the '${tmp_file}'" >&2
    exit 1
  fi
}

update_tmp_file() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Check if the correct number of non-empty arguments is passed
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    echo "${ERR} Invalid number of arguments or empty argument." >&2
    echo "${WRN} Usage: ${FUNCNAME[0]} <temporary_file>"
    exit 1
  fi

  local tmp_file="$1"

  if grep -q "${SOURCE_REPOS_OWNER}" "${tmp_file}"; then
    # Perform the replacement in the temporary file
    sed -i "s/${SOURCE_REPOS_OWNER}/${GH_ORG_NAME}/g" "${tmp_file}"

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while updating the " >&2
      echo "temporary file: ${tmp_file}" >&2
      exit 1
    fi
  else
    echo -n "${WRN} Text to be replaced '${SOURCE_REPOS_OWNER}' "
    echo "was not found in the file '${tmp_file}'."
  fi


  # Iterate through repositories
  for ((i=1; i<"${#SOURCE_REPOS[@]}"; i++)); do

    word_to_replace="${SOURCE_REPOS[i]}"
    new_word="${TARGET_REPOS[i]}"

    if grep -q "${word_to_replace}" "${tmp_file}"; then
      # Perform the replacement in the temporary file
      sed -i "s/${word_to_replace}/${new_word}/g" "${tmp_file}"

      if [[ $? -ne 0 ]]; then
	echo -n "${ERR} An error occurred while updating the " >&2
	echo "temporary file: ${tmp_file}" >&2
	exit 1
      fi
    else
      echo -n "${WRN} Text to be replaced '${word_to_replace}' "
      echo "was not found in the file '${tmp_file}'."
      exit 1
    fi
  done
}

update_repo_file_contents() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Check if the correct number of non-empty arguments is passed
  if [[ "$#" -ne 3 || -z "$1" || -z "$2" || -z "$3" ]]; then
    echo "${ERR} Invalid number of arguments or empty argument." >&2
    echo "${WRN} Usage: ${FUNCNAME[0]} <temporary_file> <file_sha> <source_file>"
    exit 1
  fi

  local tmp_file="$1"
  local file_sha="$2"
  local source_file="$3"

  gh api \
     --method PUT \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[0]}"/contents/"${source_file}" \
     --raw-field "message=update ${source_file}" \
     --raw-field "content=$(base64 < ${tmp_file})" \
     --raw-field "sha=${file_sha}" \
     --silent

  # Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo "${YUP} The ${source_file} has been updated"
  else
    echo "${ERR} An error occurred while updating the '${source_file}'" >&2
    exit 1
  fi
}

update_repo_without_cloning() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local file_sha
  local tmp_file

  # Generate two temporary files and get sha of each source file
  for source_file in "${SOURCE_FILES[@]}"; do

    # Create a temporary file
    tmp_file="$(mktemp)"
    if [[ $? -ne 0 ]]; then
      echo "${ERR} Unable to create a temporary file" >&2
      exit 1
    else
      echo "${YUP} Temporary file '${tmp_file}' has been created"
    fi

    # Remove the temporary file when the script exits
    trap "remove_tmp_file ${tmp_file}" EXIT

    # Get the file SHA
    file_sha=$(get_file_sha "${source_file}")
    if [[ $? -eq 0 ]]; then
      echo "${YUP} The SHA for the '${source_file}' file has been obtained"
    else
      echo "${file_sha}" >&2
      exit 1
    fi

    # Download the file contents to the temporary file
    download_repo_file_contents_to_tmp_file "${source_file}" "${tmp_file}"
    # Update the temporary file
    update_tmp_file "${tmp_file}"
    # Update the repository file contents
    update_repo_file_contents "${tmp_file}" "${file_sha}" "${source_file}"

    # Remove the temporary file
    if [[ -f "${tmp_file}" ]]; then
      # rm -f "${tmp_file}"
      # echo "${YUP} Temporary file ${tmp_file} has been deleted"
      echo
    fi
  done
  echo "${OK} The repo '${TARGET_REPOS[0]}' has been updated"
}

update_org_default_repo_permission() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local repo_permission="${GH_ORG_DEFAULT_REPOSITORY_PERMISSION}"

  # Update the organization settings
  gh api \
     --method PATCH \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     /orgs/"${GH_ORG_NAME}" \
     --raw-field default_repository_permission="${repo_permission}" \
     --silent

  ## Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The '${GH_ORG_NAME}' organization default repo permission "
    echo  "setting has been updated with '${repo_permission}' value"
  else
    echo -n "${ERR} An error occurred while updating the '${GH_ORG_NAME}' " >&2
    echo -n "organization default repo permission setting with " >&2
    echo "'${repo_permission}' value" >&2
    exit 1
  fi
}

update_org_members_can_fork_private_repo() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local fork_private="${GH_ORG_MEMBERS_CAN_FORK_PRIVATE_REPOSITORIES}"

  # Update the organization settings
  gh api \
     --method PATCH \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     /orgs/"${GH_ORG_NAME}" \
     --field members_can_fork_private_repositories="${fork_private}" \
     --silent

  ## Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The ${GH_ORG_NAME} organization 'members can fork private repo'"
    echo "setting has been updated with '${fork_private}' value"
  else
    echo -n "${ERR} An error occurred while updating the '${GH_ORG_NAME}' " >&2
    echo -n "organization 'members can fork private repo' setting with " >&2
    echo "'${fork_private}' value" >&2
    exit 1
  fi
}

create_team() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Creating the team
  gh api \
     --method POST \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     /orgs/"${GH_ORG_NAME}"/teams \
     --raw-field name="${GH_TEAM_NAME}" \
     --raw-field description="${GH_TEAM_DESCRIPTION}" \
     --raw-field notification_setting="${GH_TEAM_NOTIFICATIONS}" \
     --raw-field privacy="${GH_TEAM_PRIVACY}" \
     --silent

  # Checking if the operation was successful
  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The team '${GH_TEAM_NAME}' has been created "
    echo "in the organization '${GH_ORG_NAME}'."
  else
    echo "${ERR} An error occurred while creating the team '${GH_TEAM_NAME}'" >&2
    exit 1
  fi
}

create_project_from_template() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Copy project (alternatywnie skopiować projekt 45 z IS-UMK)
  gh project copy "${SOURCE_PROJECT_NUMBER}" \
     --source-owner "${SOURCE_PROJECT_OWNER}" \
     --target-owner "${GH_ORG_NAME}" \
     --title "${TARGET_PROJECT_TITLE}"

  if [[ $? -eq 0 ]]; then
    echo "${OK} The project '${TARGET_PROJECT_TITLE}' has been created"
  else
    echo -n "${ERR} An error occurred while creating the project " >&2
    echo "'${TARGET_PROJECT_TITLE}'" >&2
    exit 1
  fi
}

clone_repositories() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through repositories
  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do

    gh repo clone "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}"

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while cloning the " >&2
      echo "${GH_ORG_NAME}/${TARGET_REPOS[i]} repository" >&2
      exit 1
    fi
  done
  echo "${OK} Cloning repositories has been completed"
}

set_team_as_codeowners() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through repositories, starting from the second one because the first
  # one does not have a 'CODEOWNERS' file
  for ((i=1; i<"${#TARGET_REPOS[@]}"; i++)); do

    local file_path="${TARGET_REPOS[i]}/.github/CODEOWNERS"

    if [[ ! -w "${file_path}" ]]; then
      # Because we have 'exit 1' here, the trap won't be activated.
      echo -n "${ERR} The file ${TARGET_REPOS[i]} does not exist " >&2
      echo "or is not writable. Clone repositories first." >&2
      exit 1
    fi

    # Overwrite the first line in the CODEOWNERS file
    echo "* ${GH_ORG_NAME}/${GH_TEAM_NAME}" > "${file_path}"

    echo -n "${YUP} The CODEOWNERS file in '${TARGET_REPOS[i]}' "
    echo "has been updated to ${GH_ORG_NAME}/${GH_TEAM_NAME}."
  done
  echo "${OK} The configuration of the 'CODEOWNERS' files has been completed."
}

commit_changes_and_push_to_remote_repos() {
  # Set the commit message
  local commit_message="Assign ${GH_TEAM_NAME} as the code owners."

  # Function to execute git commands with specified git dir and work tree
  git_with_dir() {
    git --git-dir="$1/.git" --work-tree="$1" "${@:2}"
  }

  # Iterate through repositories, starting from the second one because in the first
  # one we do not change any file.
  for ((i=1; i<"${#TARGET_REPOS[@]}"; i++)); do
    local target_repo="${TARGET_REPOS[i]}"

    if [[ ! -d "${target_repo}" ]]; then
      # Because we have 'exit 1' here, the trap won't be activated.
      echo -n "${ERR} The directory ${target_repo} does not exist." >&2
      echo "Clone repositories first." >&2
      exit 1
    fi

    # Add changes to the staging area
    git_with_dir "${target_repo}" add .

    # Check if there are changes to commit
    if git_with_dir "${target_repo}" diff --staged --quiet; then
      echo -n "${WRN} Surprisingly, ${target_repo} repository "
      echo "doesn't have any changes to commit."
      exit 1
    else
      # Commit the changes
      git_with_dir "${target_repo}" commit -m "${commit_message}"

      # Push the changes to the remote repository
      git_with_dir "${target_repo}" push origin "${GH_REPO_BRANCH}"

      echo -n "${YUP} Changes made in the ${target_repo} directory "
      echo "have been pushed to the remote repository."
    fi
  done
  echo -n "${OK} Commit and push changes to remote repositories "
  echo "have been completed."
}

lock_branch() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through the repositories, starting from the second one because the
  # first one does not contain assignments for students and so does not need the
  # branch to be locked
  for ((i=1; i<"${#TARGET_REPOS[@]}"; i++)); do

    # Branch protection rule setup: lock branch
    gh api \
       --method PUT \
       --header "Accept: ${GH_API_ACCEPT_HEADER}" \
       --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
       repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[i]}"/branches/"${GH_REPO_BRANCH}"/protection \
       --field required_status_checks='null' \
       --field enforce_admins='null' \
       --field required_pull_request_reviews='null' \
       --field restrictions='null' \
       --field lock_branch='true' \
       --silent

    # Check whether the operation was completed
    if [[ $? -eq 0 ]]; then
      echo -n "${YUP} The branch protection rule 'lock branch' "
      echo -n "for the '${GH_REPO_BRANCH}' branch on the repository "
      echo "${GH_ORG_NAME}/${TARGET_REPOS[i]} has been set."
    else
      echo "${ERR} An error occurred while setting branch protection rule." >&2
      exit 1
    fi
  done
  echo "${OK} Branch protection rule 'lock branch ' setup completed."
}

require_conversation_resolution_before_merging() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Iterate through the repositories, starting from the second one because the
  # first one does not contain assignments for students and so does not need the
  # branch rule to be set to 'require conversation resolution before merging'.
  for ((i=1; i<"${#TARGET_REPOS[@]}"; i++)); do

    # Branch protection rule setup: Require conversation resolution before merging
    gh api \
       --method PUT \
       --header "Accept: ${GH_API_ACCEPT_HEADER}" \
       --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
       repos/"${GH_ORG_NAME}"/"${TARGET_REPOS[i]}"/branches/"${GH_REPO_BRANCH}"/protection \
       --field required_status_checks='null' \
       --field enforce_admins='null' \
       --field required_pull_request_reviews='null' \
       --field restrictions='null' \
       --field required_conversation_resolution='true' \
       --silent

    # Check whether the operation was successful
    if [[ $? -eq 0 ]]; then
      echo -n "${YUP} The branch protection rule "
      echo -n "'Require conversation resolution before merging' for the "
      echo -n "'${GH_REPO_BRANCH}' branch on the repository "
      echo "${GH_ORG_NAME}/${TARGET_REPOS[i]} has been set."
    else
      echo -n "${ERR} An error occurred while setting up " >&2
      echo "the branch protection rule." >&2
      exit 1
    fi
  done
  echo -n "${OK} Branch protection rule "
  echo "'Require conversation resolution before merging' setup completed."
}

# Retrieves the project ID for a specified project title within a GitHub
# organization.
get_project_id() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Local variable declaration for the return value
  local project_id

  # List projects under a specific organization and extract the project ID using
  # jq based on the title.
  project_id=$(gh project list \
                  --owner "${GH_ORG_NAME}" \
                  --format 'json' \
                  --jq ".projects[] | select(.title == \"${TARGET_PROJECT_TITLE}\") | .id")

  if [[ $? -eq 0 ]]; then
    if [[ -n "${project_id}" ]]; then
      echo "${project_id}"
    else
      echo -n "${ERR} The obtained ID of the '${TARGET_PROJECT_TITLE}' project "
      echo -n "is empty: the '${GH_ORG_NAME}' organization has no such project. "
      echo -n "Check the 'user_config' file to see if you have entered "
      echo "the 'GH_ORG_NAME' and 'TARGET_PROJECT_TITLE' correctly."
      exit 1
    fi
  else
    echo -n "${ERR} An error occurred while obtaining the ID of the "
    echo -n "'${TARGET_PROJECT_TITLE}' project from the '${GH_ORG_NAME}' "
    echo "organization."
    exit 1
  fi
}

# Retrieves the team ID for a specified team name within a GitHub organization.
get_team_id() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Local variable declaration for the return value
  local team_id

  # Define a GraphQL query to retrieve the team ID from the GitHub API.
  local query="
  {
    organization(login: \"${GH_ORG_NAME}\") {
      team(slug: \"${GH_TEAM_NAME}\") {
        id
      }
    }
  }
  "

  # Execute the GraphQL query and extract the team ID using
  # jq.
  team_id=$(gh api graphql \
               --raw-field query="${query}" \
               --jq '.data.organization.team.id')

  if [[ $? -eq 0 ]]; then
    if [[ -n "${team_id}" ]]; then
      echo "${team_id}"
    else
      echo -n "${ERR} The obtained ID of the '${GH_TEAM_NAME}' team "
      echo -n "is empty: the '${GH_ORG_NAME}' organization has no such team. "
      echo -n "Check the 'user_config' file to see if you have entered "
      echo "the 'GH_ORG_NAME' and 'GH_TEAM_NAME' correctly."
      exit 1
    fi
  else
    echo -n "${ERR} An error occurred while obtaining the ID of the "
    echo "'${GH_TEAM_NAME}' team from the '${GH_ORG_NAME}' organization"
    exit 1
  fi
}

# Links a specified project to a specified team within a GitHub organization.
link_project_to_team() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit

  # Local variable declarations
  local project_id
  local team_id

  # Retrieve the project ID.
  project_id=$(get_project_id)

  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the ID of the '${TARGET_PROJECT_TITLE}' project"
    echo " has been completed"
  else
    echo "${project_id}" >&2
    exit 1
  fi

  # Retrieve the team ID
  team_id=$(get_team_id)

  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the ID of the '${GH_TEAM_NAME}' team"
    echo " has been completed"
  else
    echo "${team_id}" >&2
    exit 1
  fi

  # Define a GraphQL mutation to link the project to the team.
  local query="
    mutation {
      linkProjectV2ToTeam(input: {
        teamId: \"${team_id}\",
        projectId: \"${project_id}\",
      }) {
          clientMutationId
         }
    }
    "

  # Execute the GraphQL mutation using the GitHub CLI.
  gh api graphql \
     --raw-field query="${query}" \
     --silent

  # Check the exit status of the last command to verify if the link operation
  # was successful.
  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The '${TARGET_PROJECT_TITLE}' project has been linked "
    echo "to the '${GH_TEAM_NAME}' team"
  else
    echo -n "${ERR} An error occurred while linking the " >&2
    echo "'${TARGET_PROJECT_TITLE}' project to the '${GH_TEAM_NAME}' team" >&2
    exit 1
  fi
}

get_user_id() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit

  # Check if the correct number of non-empty arguments is passed
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    echo "${ERR} Invalid number of arguments or empty argument." >&2
    echo "${WRN} Usage: ${FUNCNAME[0]} <github_login>"
    exit 1
  fi

  local gh_login="$1"

  # Local variable declaration for the return value
  local user_id

  local query="
  {
    user(login: \"${gh_login}\") {
      id
    }
  }
  "

  user_id=$(gh api graphql \
               --raw-field query="${query}" \
               --jq '.data.user.id')

  if [[ $? -eq 0 ]]; then
    if [[ -n "${user_id}" ]]; then
      echo "${user_id}"
    else
      echo -n "${ERR} The obtained ID of the '${gh_login}' user "
      echo -n "is empty: the '${gh_login}' user does not exist. "
      echo -n "Check the 'user_config' file to see if you have entered "
      echo "the 'GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING' correctly."
      exit 1
    fi
  else
    echo -n "${ERR} An error occurred while obtaining the ID "
    echo "of the '${gh_login}' user."
    exit 1
  fi
}

enable_team_review_assignment() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit

  github_logins=("${GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING[@]}")

  local team_id
  local -a user_ids  # the array of GitHub user IDs

  team_id=$(get_team_id)

  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the ID of the '${GH_TEAM_NAME}' team"
    echo " has been completed"
  else
    echo "${team_id}" >&2
    exit 1
  fi

  # Loop through all logins and execute a GraphQL query for each of them
  for gh_login in "${github_logins[@]}"; do
    local output=$(get_user_id "${gh_login}")
    if [[ $? -eq 0 ]]; then
      user_ids+=("\"$output\"")  # Adding ID as a string to the array
      echo -n "${YUP} Obtaining the ID of the '${gh_login}' "
      echo "user has been completed"
    else
      echo "${output}" >&2
      exit 1
    fi
  done

  # TODO:
  # add checking that the user belongs to the organization
  # END:

  # Add comma between user IDs
  users_id_string=$(IFS=,; echo "${user_ids[*]}")

  local query="
    mutation {
      updateTeamReviewAssignment(input: {
        algorithm: ${GH_TEAM_REVIEW_ASSIGNMENT_ALGORITHM},
        enabled: true,
        excludedTeamMemberIds: [${users_id_string}],
        id: \"${team_id}\",
        notifyTeam: ${GH_TEAM_NOTIFY},
        teamMemberCount: ${GH_TEAM_MEMBER_COUNT},
      }) {
           clientMutationId
         }
    }
    "

  # Execute the GraphQL mutation using the GitHub CLI.
  gh api graphql \
     --header "Accept: application/vnd.github.stone-crop-preview+json" \
     --raw-field query="${query}" \
     --silent

  # Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The review assignment has benn enabled "
    echo "for the '${GH_TEAM_NAME}' team"
  else
    echo -n "${ERR} An error occurred while enabling the review " >&2
    echo "assignment for the '${GH_TEAM_NAME}' team" >&2
    exit 1
  fi
}

get_team_number() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit

  # Local variable declaration for the return value
  local team_number

  # Retrieve the team number
  team_number=$(gh api \
                   --method GET \
                   --header "Accept: ${GH_API_ACCEPT_HEADER}" \
                   --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
                   /orgs/"${GH_ORG_NAME}"/teams/"${GH_TEAM_NAME}" \
                   --jq '.id')

  if [[ $? -eq 0 ]]; then
    echo "${team_number}"
  else
    echo -n "${ERR} An error occurred while obtaining the number of the "
    echo "'${GH_TEAM_NAME}' team from the '${GH_ORG_NAME}' organization."
    exit 1
  fi
}

invite_to_organization_team() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit
  # Disable the script's trap on ERR
  trap '' ERR

  # Check if the file with emails exists and is readable
  if [ ! -r 'emails.txt' ]; then
    echo "${ERR} The file 'emails.txt' is not readable or does not exist."
    exit 1
  fi

  # Local variable declaration
  local team_number
  local team_ids
  local response
  local http_status
  local email

  # Get the team ID
  team_number=$(get_team_number)
  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the ID of the '${GH_TEAM_NAME}' team"
    echo " has been completed"
  else
    echo "${team_number}" >&2
    exit 1
  fi

  # Reading from a file
  while IFS= read -r email; do

  # Sending an invitation
  response=$(gh api \
                --method POST \
                --header "Accept: ${GH_API_ACCEPT_HEADER}" \
                --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
                /orgs/"${GH_ORG_NAME}"/invitations \
                --raw-field email="${email}" \
                --raw-field role="${GH_ORG_ROLE}" \
                --field "team_ids[]=${team_number}" \
                --include)

  # Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo "${YUP} Invitation to join the '${GH_ORG_NAME}' sent to: ${email}."
  else
    # Extract the HTTP status code from the first line of the 'response' and and
    # look for '422'
    http_status=$(echo "${response}" | grep --max-count=1 -o '422')

    if [[ "${http_status}" -eq 422 ]]; then
      echo -n "${WRN} The invitation to '${email}' has not been sent. The email "
      echo -n "address is not valid, or the variable 'GH_ORG_ROLE' from "
      echo -n "'system_config.sh' is not valid, or the user with this email may "
      echo -n "already be a member of the '${GH_ORG_NAME}' organization. If the "
      echo -n "latter, add the user to the '${GH_TEAM_NAME}' team manually or send "
      echo -n "the link https://github.com/orgs/${GH_ORG_NAME}/teams/${GH_TEAM_NAME}"
      echo " to the user so he/she can request to join the team."
    else
      echo -n "${ERR} Failed to send the '${GH_ORG_NAME}' invitation " >&2
      echo "to: ${email}" >&2
      exit 1
    fi
  fi
  done < 'emails.txt'
}

# Retrieves the project ID for a specified project title within a GitHub
# organization.
get_project_number() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  # Local variable declaration for the return value
  local project_number

  # List projects under a specific organization and extract the project ID using
  # jq based on the title.
  project_number=$(gh project list \
                  --owner "${GH_ORG_NAME}" \
                  --format 'json' \
                  --jq ".projects[] | select(.title == \"${TARGET_PROJECT_TITLE}\") | .number")

  if [[ $? -eq 0 ]]; then
    if [[ -n "${project_number}" ]]; then
      echo "${project_number}"
    else
      echo -n "${ERR} The '${TARGET_PROJECT_TITLE}' project within the "
      echo -n "'${GH_ORG_NAME}' organization might have been closed or "
      echo -n "does not exist, as the obtained number for this project "
      echo -n "is empty: the '${GH_ORG_NAME}' organization has no such "
      echo -n "open project. Check the 'user_config' file to ensure "
      echo -n "that you have correctly entered 'GH_ORG_NAME' and "
      echo "'TARGET_PROJECT_TITLE'."
      exit 1
    fi
  else
    echo -n "${ERR} An error occurred while obtaining the number of the "
    echo -n "'${TARGET_PROJECT_TITLE}' project from the '${GH_ORG_NAME}' "
    echo "organization."
    exit 1
  fi
}

get_project_data_as_json() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local project_number

  timestamp=$(date "+%F-%H-%M-%S")
  filename="${TARGET_PROJECT_TITLE}-${timestamp}.json"

  # Check if the file can be created
  if [[ -e "${filename}" ]]; then
    echo "${ERR} File '${filename}' already exists."
    exit 1
  elif ! touch "${filename}" &>/dev/null; then
    echo -n "${ERR} File '${filename}' cannot be created. "
    echo "Check permissions or disk space."
    exit 1
  fi

  project_number=$(get_project_number)
  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the number of the '${TARGET_PROJECT_TITLE}' "
    echo "project has been completed"
  else
    echo "${project_number}" >&2
    exit 1
  fi

  gh project item-list "${project_number}" \
   --owner "${GH_ORG_NAME}" \
   --format json | jq '.' > "${filename}"

  if [[ $? -eq 0 ]]; then
    echo -n "${OK} The project '${TARGET_PROJECT_TITLE}' has been logged "
    echo "to the file: ${filename}"
  else
    echo -n "${ERR} An error occurred while logging the project " >&2
    echo "'${TARGET_PROJECT_TITLE}'" >&2
    exit 1
  fi
}

close_project() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local project_number

  project_number=$(get_project_number)
  if [[ $? -eq 0 ]]; then
    echo -n "${YUP} Obtaining the number of the '${TARGET_PROJECT_TITLE}' "
    echo "project has been completed"
  else
    echo "${project_number}" >&2
    exit 1
  fi

  gh project close "${project_number}" \
     --owner "${GH_ORG_NAME}"

  if [[ $? -eq 0 ]]; then
    echo "${OK} The project '${TARGET_PROJECT_TITLE}' has been closed"
  else
    echo -n "${ERR} An error occurred while closing the project " >&2
    echo "'${TARGET_PROJECT_TITLE}'" >&2
    exit 1
  fi
}

create_repo_from_template() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  for ((i=0; i<"${#SOURCE_REPOS[@]}"; i++)); do

    # Create private repo from the template without cloning it.
    gh repo create "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}" \
       --private \
       --template "${GH_ORG_NAME}"/"${SOURCE_REPOS[i]}" \
       --clone=false

    if [[ $? -ne 0 ]]; then
      echo -n "${ERR} An error occurred while creating the " >&2
      echo "${GH_ORG_NAME}/${TARGET_REPOS[i]} repo from the " >&2
      echo "${GH_ORG_NAME}/${SOURCE_REPOS[i]} template" >&2
      exit 1
    fi
  done
  echo "${OK} Creating repos from templates has been completed"
}


# TODO:
# For tests
# END:

assign_repo_to_team() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  local repo="$1"
  
  # Add a repository to the team
  gh api \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     --method PUT \
     /orgs/"${GH_ORG_NAME}"/teams/"${GH_TEAM_NAME}"/repos/"${GH_ORG_NAME}"/"${repo}" \
     --raw-field permission="${GH_TEAM_REPO_PERMISSION}" \
     --silent

  # Check if the command succeeded
  if [[ $? -eq 0 ]]; then
    echo -n "Repository '${repo}' was successfully added to "
    echo "the '${GH_TEAM_NAME}' team."
  else
    echo -n "${ERR} An error occurred while adding the repository '${repo}' " >&2
    echo "to the '${GH_TEAM_NAME}' team in the '${GH_ORG_NAME}' organization." >&2
    exit 1
  fi
}

delete_team() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit
  echo "Deleting the '${GH_TEAM_NAME}' team from the '${GH_ORG_NAME}' organization"
  exit
  gh api \
     --method DELETE \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     /orgs/"${GH_ORG_NAME}"/teams/"${GH_TEAM_NAME}" \
     --silent

  # Check whether the operation was successful
    if [[ $? -eq 0 ]]; then
      echo -n "${OK} The '${GH_TEAM_NAME}' team has been deleted "
      echo "from the '${GH_ORG_NAME}' organization."
    else
      echo -n "${ERR} An error occurred while deleting the '${GH_TEAM_NAME}'" >&2
      echo " team from the '${GH_ORG_NAME}' organization." >&2
      exit 1
    fi
}

delete_organization() {
  # Disable the script's abort-on-first-error feature.
  set +o errexit

  gh api \
     --method DELETE \
     --header "Accept: ${GH_API_ACCEPT_HEADER}" \
     --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
     /orgs/"${GH_ORG_NAME}" \
     --silent

  # Check whether the operation was successful
  if [[ $? -eq 0 ]]; then
    echo "${OK} The '${GH_ORG_NAME}' organization has been deleted "
  else
    echo -n "${ERR} An error occurred while deleting the " >&2
    echo "'${GH_ORG_NAME}' organization" >&2
    exit 1
  fi
}

# VALIDATION FUNCTIONS----------------------------------------------------------#
# Check if GitHub CLI (gh) is installed
check_if_gh_installed() {
  if ! command -v gh &> /dev/null; then
    echo -n "${ERR} GitHub CLI (gh) is not installed on your computer. " >&2
    echo "Install to continue: https://cli.github.com/" >&2
  else
    echo "${YUP} 'GitHub CLI (gh)' is installed on your computer."
  fi
}

# Check if Git is installed
check_if_git_installed() {
  if ! command -v git &> /dev/null; then
    echo -n "${ERR} 'git' is not installed on your computer. " >&2
    echo "Install to continue: https://www.git-scm.com/downloads" >&2
  else
    echo "${YUP} 'git' is installed on your computer."
  fi
}

check_if_sed_installed() {
  if ! command -v sed &> /dev/null; then
    echo -n "${ERR} 'sed' – a command-line utility for parsing and " >&2
    echo -n "transforming text is not installed. Install it to continue: " >&2
    echo "https://www.gnu.org/software/sed/" >&2
  else
    echo "${YUP} 'sed' is installed on your computer."
  fi
}

check_if_grep_installed() {
  if ! command -v grep &> /dev/null; then
    echo -n "${ERR} 'grep' – a command-line utility for searching text " >&2
    echo -n "that match a regular expression is not installed. " >&2
    echo "Install it to continue:https://www.gnu.org/software/grep/ " >&2
  else
    echo "${YUP} 'grep' is installed on your computer."
  fi
}

check_if_jq_installed() {
  if ! command -v jq &> /dev/null; then
    echo -n "${ERR} 'jq' – a lightweight and flexible command-line JSON " >&2
    echo -n "processor is not installed. Install it to continue. " >&2
    echo "https://stedolan.github.io/jq/download/" >&2
  else
    echo "${YUP} 'jq' is installed on your computer."
  fi
}

check_if_date_installed() {
  if ! command -v date &> /dev/null; then
    echo -n "${ERR} 'date' – a command-line utility for displaying the " >&2
    echo -n "system date and time is not installed. Install it to continue. " >&2
    echo "https://www.gnu.org/software/coreutils/" >&2
  else
    echo "${YUP} 'date' is installed on your computer."
  fi
}

check_if_touch_installed() {
  if ! command -v touch &> /dev/null; then
    echo -n "${ERR} 'touch' – a command-line utility for changing file " >&2
    echo -n "timestamps is not installed. Install it to continue. " >&2
    echo "https://www.gnu.org/software/coreutils/" >&2
  else
    echo "${YUP} 'touch' is installed on your computer."
  fi
}

# TODO:
# Add '${FUNCNAME[0]}' to the error messages instead of the function name
# END:

# Function to validate non-empty strings
validate_non_empty_string() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_non_empty_string' function." >&2
    exit 1
  fi

  local var_name="$1"
  local var_value="$2"

  if [[ -z "${var_value}" ]]; then
    echo "${ERR} '${var_name}' is empty." >&2
  else
    echo "${YUP} '${var_name}' is non-empty: ${var_value}."
  fi
}

validate_url_compatibility() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_url_compatibility' function." >&2
    exit 1
  fi

  local var_name="$1"
  local var_value="$2"

  if [[ "${var_value}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "${YUP} '${var_name}' has valid URL value: ${var_value}."
  else
    echo "${ERR} '${var_name}' has invalid URL value: ${var_value}." >&2
  fi
}

# Function to validate numeric values
validate_numeric() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_numeric' function." >&2
    exit 1
  fi

  local var_name="$1"
  local var_value="$2"

  if ! [[ "${var_value}" =~ ^[0-9]+$ ]]; then
    echo "${ERR} '${var_name}' has not numeric value: ${var_value}." >&2
  else
    echo "${YUP} '${var_name}' has numeric value: ${var_value}."
  fi
}

# Function to validate non-empty arrays
validate_non_empty_array() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_non_empty_array' function." >&2
    exit 1
  fi

  local var_name="$1"
  shift # Remove the first argument to treat the rest as an array
  local -a arr=("$@")

  if [[ "${#arr[@]}" -eq 0 ]]; then
    echo "${ERR} '${var_name}' is an empty array." >&2
  else
    echo "${YUP} '${var_name}' is a non-empty array: ${arr[@]}."
  fi
}

# Function to validate no empty elements in arrays
validate_no_empty_elements() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_no_empty_elements' function." >&2
    exit 1
  fi

  local var_name="$1"
  shift # Remove the first argument to treat the rest as an array
  local -a arr=("$@")

  for element in "${arr[@]}"; do
    if [[ -z "${element}" ]]; then
      echo "${ERR} '${var_name}' contains an empty element." >&2
      return
    fi
  done
  echo "${YUP} '${var_name}' has no empty elements."
}

# Function to validate URL compatibility for each element in an array
validate_array_elements_url_compatibility() {
  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_array_elements_url_compatibility' function." >&2
    exit 1
  fi

  local var_name="$1"
  shift # Remove the first argument to treat the rest as an array
  local -a arr=("$@")

  for element in "${arr[@]}"; do
    if ! [[ "${element}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
      echo "${ERR} '${var_name}' contains a non-compatible URL element: ${element}." >&2
      return
    fi
  done
  echo "${YUP}  All elements in '${var_name}' are compatible with URL."
}

# Function to check for duplicate elements in an array
validate_no_duplicates() {
  # Evaluation of the 'validate_no_duplicates' function needs 'set +u',
  # otherwise will be terminated by 'set -u'
  local is_set_nounset=''

  [[ "$-" == *u* ]] && is_set_nounset='true' || is_set_nounset='false'
  set +u  

  if [[ "$#" -lt 2 ]]; then
    echo -n "${ERR} Insufficient arguments provided for the " >&2
    echo "'validate_no_duplicates' function." >&2
    exit 1
  fi

  local var_name="$1"
  shift # Remove the first argument to treat the rest as an array
  local -a arr=("$@")
  local -A arr_map=()

  for element in "${arr[@]}"; do
    if [[ -n "${arr_map[${element}]}" ]]; then
      echo "${ERR} '${var_name}' has duplicate elements: ${element}." >&2
      return
    fi
    arr_map["${element}"]=1
  done
  echo "${YUP} '${var_name}' has no duplicates."
  "${is_set_nounset}" || set +u
}

# TODO:
# Add function validations on global variables from system_config.sh
# END:

# THE MAIN COMMANDS-------------------------------------------------------------#
# TODO:
# Add reqest for confirmation before deleting the organization: user should
# rewrite the name of the organization for deletion
# END:
delete() {

  if [[ -f 'user_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'system_config.sh' "
    echo -n "file is missing. Please run the 'gh soc init' command "
    echo "to create the missing file(s)."
    exit 1
  fi

  # Archive data before deleting the organization
  echo 'Running get_project_data_as_json()'
  get_project_data_as_json

  # Asking the user for confirmation for deleting the organization
  echo -n "${WRN} Are you sure you want to delete the organization "
  echo "'${GH_ORG_NAME}'? (no/yes) [no]:"
  read user_confirm

  # Setting default choice
  if [ -z "${user_confirm}" ]; then
    user_confirm='no'
  fi

  if [[ "${user_confirm}" == 'yes' ]]; then
    echo 'Running delete_organization()'
    delete_organization
  fi
}

reopen() {

  if [[ -f 'user_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'system_config.sh' "
    echo -n "file is missing. Please run the 'gh soc init' command "
    echo "to create the missing file(s)."
    exit 1
  fi

  SOURCE_REPOS_OWNER="${GH_ORG_NAME}"
  SOURCE_REPOS=("${TARGET_REPOS[@]}")
  TARGET_REPOS=("${SUCCESSOR_REPOS[@]}")

  echo 'Running check_if_source_repos_exist()'
  check_if_source_repos_exist
  echo 'Running check_if_target_repos_noexist()'
  check_if_target_repos_noexist

  echo 'Running create_repo_from_template()'
  create_repo_from_template

  echo 'Running create_team()'
  create_team

  # TODO:
  # Translate from Polish to English
  # END:
  
  # W IS-UMK mamy w insight możliwość tworzenia wykresów gdzie x to time. Ja na
  # swoim koncie 'pierzcham' nie mam takiej możliwości i dlatego, gdy kopiuje z
  # @pierzcham na konto 'soc-test' to tracę dwa ostatnie wykresy. Potrzebne jest
  # konto organizacja na planie TEAM
  # https://github.com/orgs/IS-UMK/projects/45
  echo 'Running create_project_from_template()'
  create_project_from_template

  # Domyślnie ustawia uprawnienia zespołu do projektu na read, ale może warto
  # zmienić ustawienia Ogranizacji: Settings –> Member privileges –> Projects base
  # permissions [Read] "Projects created by members will default to the elected
  # role."
  # get_team_id – gh api graphql
  # link_project_to_team – gh api graphql
  echo 'Running link_project_to_team()'
  link_project_to_team

  # UpdateTeamReviewAssignmentInput is available under the Team review
  # assignments preview. During the preview period, the API may change without
  # notice.
  # https://docs.github.com/en/graphql/reference/mutations#updateteamreviewassignment
  # https://docs.github.com/en/graphql/reference/input-objects#updateteamreviewassignmentinput

  # TeamReviewAssignmentAlgorithm is available under the Team review
  # assignments preview. During the preview period, the API may change without
  # notice. \"$TeamReviewAssignmentAlgorithm\",
  # get_team_id – gh api graphql
  # enable_team_review_assignment – gh api graphql
  echo 'Running enable_team_review_assignment()'
  enable_team_review_assignment

  # # This API operation needs the "admin:org" scope which is not set by default. To
  # # request it, run: gh auth refresh -h github.com -s admin:org
  echo 'Running invite_to_organization_team()'
  invite_to_organization_team

  echo 'Running create_repo_from_temaplate()'
  create_repo_from_temaplate

  echo 'Running set_repo_as_private_template()'
  set_repo_as_private_template

  echo 'Running set_repos_descriptions()'
  set_repos_descriptions

  echo 'Running update_repo_without_cloning()'
  update_repo_without_cloning

  # GitHub Pages is available in private repositories with GitHub Pro, GitHub
  # Team, GitHub Enterprise Cloud, and GitHub Enterprise Server.
  echo 'Running swich_on_gh_pages()'
  swich_on_gh_pages

  echo 'Running set_website_link()'
  set_repos_website

  # !!!Wymagane jest uruchomienie init w celu utworzenia target repositories na
  # koncie ogranizacji GH_ORG_NAME – wyszystkie poniżej funkcje zależą od tego!!!!
  echo 'Running clone_repositories()'
  clone_repositories

  # !!!!!!!These features require local repositories!!!!!!!!!!!!!!!!!!!!!

  # # [GitHub docs]: You can define code owners in public repositories with GitHub
  # # Free and GitHub Free for organizations, and in public and private
  # # repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and
  # # GitHub Enterprise Server.
  echo 'Running set_team_as_codeowners()'
  set_team_as_codeowners

  echo 'Running commit_changes_and_push_to_remote_repos()'
  commit_changes_and_push_to_remote_repos
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  # # [GitHub docs]: Protected branches are available in public repositories with
  # # GitHub Free and GitHub Free for organizations, and in public and private
  # # repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and
  # # GitHub Enterprise Server.
  # # [GitHub docs]: Branch is read-only. Users cannot push to the branch.
  echo 'Running lock_branch()'
  lock_branch

  # [GitHub docs]: When enabled, all conversations on code must be resolved before
  # a pull request can be merged into a branch that matches this rule
  echo 'Running require_conversation_resolution_before_merging()'
  require_conversation_resolution_before_merging
}

close() {

  if [[ -f 'user_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'system_config.sh' "
    echo -n "file is missing. Please run the 'gh soc init' command "
    echo "to create the missing file(s)."
    exit 1
  fi

  # Archive data before closing the project
  echo 'Running get_project_data_as_json()'
  get_project_data_as_json

  echo 'Running close_project()'
  close_project

  # Asking the user for confirmation for deleting the team
  echo -n "${WRN} Are you sure you want to delete the team '${GH_TEAM_NAME}' "
  echo "from organization '${GH_ORG_NAME}'? (no/yes) [no]:"
  read user_confirm

  # Setting default choice
  if [[ -z "${user_confirm}" ]]; then
    user_confirm='no'
  fi

  if [[ "${user_confirm}" == 'yes' ]]; then
    echo 'Running delete_team()'
    delete_team
  fi
}

log() {

  if [[ -f 'user_config.sh' ]]; then
    source user_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' file is missing. Please run "
    echo "the 'gh soc init' command to create the missing file."
    exit 1
  fi

  echo 'Running get_project_data_as_json()'
  get_project_data_as_json
}

assign() {

  if [[ -f 'user_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'system_config.sh' "
    echo -n "file is missing. Please run the 'gh soc init' command "
    echo "to create the missing file(s)."
    exit 1
  fi

  local repo="$1"

  echo 'Running add_repo_to_team()'
  assign_repo_to_team "${repo}"
}

open() {

  if [[ -f 'user_config.sh' && -f 'source_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source source_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'source_config.sh' and/or "
    echo -n "'system_config.sh' file is missing. Please run the 'gh soc init' "
    echo "command to create the missing file(s)."
    exit 1
  fi

  # Check if the user has the required token scopes defined in the
  # 'GH_TOKEN_SCOPES' in th 'system_config.sh' file.
  check_if_gh_has_required_token_scopes

  # Można dodać ustawienia 'Projects base permissions' na 'read', ale to
  # wymagałoby użycie graphql
  echo 'Running update_org_default_repo_permission()'
  update_org_default_repo_permission
  echo 'Running update_org_members_can_fork_private_repo()'
  update_org_members_can_fork_private_repo

  echo 'Running create_team()'
  create_team

  # W IS-UMK mamy w insight możliwość tworzenia wykresów gdzie x to time. Ja na
  # swoim koncie 'pierzcham' nie mam takiej możliwości i dlatego, gdy kopiuje z
  # @pierzcham na konto 'soc-test' to tracę dwa ostatnie wykresy. Potrzebne jest
  # konto organizacja na planie TEAM. Jedyna funkcja, kóra zależy od
  # 'source_config.sh'.
  # TODO:
  # Może przenieść create_project_from_template do 'sync' ze względu na
  # zależność od 'source_config.sh'.?
  # END:
  # https://github.com/orgs/IS-UMK/projects/45
  echo 'Running create_project_from_template()'
  create_project_from_template

  # Domyślnie ustawia uprawnienia zespołu do projektu na read, ale może warto
  # zmienić ustawienia Ogranizacji: Settings –> Member privileges –> Projects base
  # permissions [Read] "Projects created by members will default to the elected
  # role."
  # get_team_id – gh api graphql
  # link_project_to_team – gh api graphql
  echo 'Running link_project_to_team()'
  link_project_to_team

  # UpdateTeamReviewAssignmentInput is available under the Team review
  # assignments preview. During the preview period, the API may change without
  # notice.
  # https://docs.github.com/en/graphql/reference/mutations#updateteamreviewassignment
  # https://docs.github.com/en/graphql/reference/input-objects#updateteamreviewassignmentinput

  # TeamReviewAssignmentAlgorithm is available under the Team review
  # assignments preview. During the preview period, the API may change without
  # notice. \"$TeamReviewAssignmentAlgorithm\",
  # get_team_id – gh api graphql
  # enable_team_review_assignment – gh api graphql
  echo 'Running enable_team_review_assignment()'
  enable_team_review_assignment

  # # This API operation needs the "admin:org" scope which is not set by default. To
  # # request it, run: gh auth refresh -h github.com -s admin:org
  echo 'Running invite_to_organization_team()'
  invite_to_organization_team

  # !!!Wymagane jest uruchomienie init w celu utworzenia target repositories na
  # koncie organizacji GH_ORG_NAME – wyszystkie poniżej funkcje zależą od tego!!!!
  echo 'Running clone_repositories()'
  clone_repositories

  # !!!!!!!These functions require local repositories!!!!!!!!!!!!!!!!!!!!!

  # # [GitHub docs]: You can define code owners in public repositories with GitHub
  # # Free and GitHub Free for organizations, and in public and private
  # # repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and
  # # GitHub Enterprise Server.
  echo 'Running set_team_as_codeowners()'
  set_team_as_codeowners

  echo 'Running commit_changes_and_push_to_remote_repos()'
  commit_changes_and_push_to_remote_repos
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  # # [GitHub docs]: Protected branches are available in public repositories with
  # # GitHub Free and GitHub Free for organizations, and in public and private
  # # repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and
  # # GitHub Enterprise Server.
  # # [GitHub docs]: Branch is read-only. Users cannot push to the branch.
  echo 'Running lock_branch()'
  lock_branch

  # [GitHub docs]: When enabled, all conversations on code must be resolved before
  # a pull request can be merged into a branch that matches this rule
  echo 'Running require_conversation_resolution_before_merging()'
  require_conversation_resolution_before_merging
}

sync() {

  if [[ -f 'user_config.sh' && -f 'source_config.sh' && -f 'system_config.sh' ]]; then
    source user_config.sh
    source source_config.sh
    source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'source_config.sh' and/or "
    echo -n "'system_config.sh' file is missing. Please run the 'gh soc init' "
    echo "command to create the missing file(s)."
    exit 1
  fi

  # Check if the user has the required token scopes defined in the
  # 'GH_TOKEN_SCOPES' in th 'system_config.sh' file.
  check_if_gh_has_required_token_scopes

  # Source repositories validation
  # Check if the source repositories exist so that we can fork them. We can't
  # start repos forking if one of these doesn't exist.
  echo 'Running check_if_source_repos_exist()'
  check_if_source_repos_exist
  # Target repositories validation
  # Check if the target repositories not yet exist so that we can create them
  echo 'Running check_if_target_repos_noexist()'
  check_if_target_repos_noexist
  exit
  # Fork the main repository and all materials linked in the 'Repository
  # for lab & home activities' column in the README.md and defined in the
  # 'SOURCE_REPOS' array in the 'source_config.sh' file.
  echo 'Running fork_repositories()'
  fork_repositories
  echo 'Running set_repo_as_private_template()'
  set_repo_as_private_template
  echo 'Running set_repos_descriptions()'
  set_repos_descriptions
  echo 'Running update_repo_without_cloning()'
  update_repo_without_cloning

  # GitHub Pages is available in private repositories with GitHub Pro, GitHub
  # Team, GitHub Enterprise Cloud, and GitHub Enterprise Server.
  echo 'Running swich_on_gh_pages()'
  swich_on_gh_pages
  echo 'Running set_website_link()'
  set_repos_website
}

precheck() {
  # Disable the script's abort-on-first-error feature to handle errors manually.
  set +o errexit

  if [[ -f 'user_config.sh' && -f 'source_config.sh' ]]; then
    source user_config.sh
    source source_config.sh
    # source system_config.sh
  else
    echo -n "${WRN} The 'user_config.sh' and/or 'source_config.sh' file is missing."
    echo " Please run the 'gh soc init' command to create the missing file(s)."
    exit 1
  fi

  echo "Commands validation:"
  check_if_gh_installed
  check_if_git_installed
  check_if_sed_installed
  check_if_grep_installed
  check_if_jq_installed
  check_if_date_installed
  check_if_touch_installed

  echo "Validation of global variables from the 'user_config.sh' file:"
  # Variables validations
  validate_url_compatibility "GH_ORG_NAME" "${GH_ORG_NAME}"
  validate_url_compatibility "GH_TEAM_NAME" "${GH_TEAM_NAME}"

  # TODO:
  # This variable can be empty, but the names must be consistent with the URL
  # validate_url_compatibility "GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING"
  # END:

  validate_non_empty_string "TARGET_PROJECT_TITLE" "${TARGET_PROJECT_TITLE}"

  # Arrays validations
  echo
  validate_non_empty_array "TARGET_REPOS" "${TARGET_REPOS[@]}"
  echo
  validate_no_empty_elements "TARGET_REPOS" "${TARGET_REPOS[@]}"
  validate_array_elements_url_compatibility "TARGET_REPOS" "${TARGET_REPOS[@]}"
  validate_no_duplicates "TARGET_REPOS" "${TARGET_REPOS[@]}"

  echo "Validation of global variables from the 'source_config.sh' file:"
  # Variable validations
  validate_url_compatibility "SOURCE_REPOS_OWNER" "${SOURCE_REPOS_OWNER}"
  validate_url_compatibility "SOURCE_PROJECT_OWNER" "${SOURCE_PROJECT_OWNER}"
  validate_numeric "SOURCE_PROJECT_NUMBER" "${SOURCE_PROJECT_NUMBER}"

  # Arrays validations
  echo
  validate_non_empty_array "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
  echo
  validate_no_empty_elements "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
  validate_array_elements_url_compatibility "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
  validate_no_duplicates "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
  validate_non_empty_array "SOURCE_FILES" "${SOURCE_FILES[@]}"
  validate_no_empty_elements "SOURCE_FILES" "${SOURCE_FILES[@]}"
  validate_no_duplicates "SOURCE_FILES" "${SOURCE_FILES[@]}"
}

init() {
# Create directory if it doesn't already exist
mkdir -p logs

# Define the path for configuration files
local user_config_path="./user_config.sh"
local source_config_path="./source_config.sh"
local system_config_path="./system_config.sh"

# Define the path for emails file
local emails_path="./emails.txt"

# Check if the emails.txt file already exists, if not, create it with
# example values
if [[ ! -f "${emails_path}" ]]; then
cat << 'EOF' > "${emails_path}"
first@example.com
second@example.com
third@example.com
EOF
else
  echo "${WRN} The file ${emails_path} already exists."
fi

# Check if the user_config.sh file already exists, if not, create it with
# default values
if [[ ! -f "${user_config_path}" ]]; then
cat << 'EOF' > "${user_config_path}"
# ORGANIZATION CONFIGS----------------------------------------------------------#
readonly GH_ORG_NAME='' # insert here your GitHub organization name

# TEAM CONFIGS------------------------------------------------------------------#
# Insert your GitHub team name and others between quotes. The name may contain
# only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the
# digits 0 through 9, the hyphen-minus character ('-'), and the underscore
# ('_').
readonly GH_TEAM_NAME='SoC-DS'
readonly GH_TEAM_DESCRIPTION='SoC Data Science Course'
readonly GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING=()

# REPOSITORY CONFIGS------------------------------------------------------------#
readonly TARGET_REPO_DESCRIPTION='SoC Data Science Course'

# New repository names: rename according to your preferences, but choose names
# that are not part of others. The first repository name may be an exception, as
# in our example: the repository name 'soc-datascience' is part of others. Names
# may contain only the ASCII letters 'a' through 'z' (in a case-insensitive
# manner), the digits 0 through 9, the dot ('.'), the hyphen-minus character
# ('-'), and the underscore ('_').
TARGET_REPOS=(
  'soc-datascience'
  'soc-datascience-hello'
  'soc-datascience-viz'
  'soc-datascience-wrang'
  'soc-datascience-spatial'
  'soc-datascience-reshape'
  'soc-datascience-paradox'
  'soc-datascience-collabor'
  'soc-datascience-scrap'
  'soc-datascience-bias'
  'soc-datascience-fitting'
  'soc-datascience-nfitting'
  'soc-datascience-valid'
  'soc-datascience-hypo'
  'soc-datascience-wrapup'
  'soc-datascience-project'
)

readonly SUCCESSOR_REPOS_SUFFIX=$(date "+%Y")
declare -a SUCCESSOR_REPOS

for ((i=0; i<${#TARGET_REPOS[@]}; i++)); do
  SUCCESSOR_REPOS+=("${TARGET_REPOS[i]}-${SUCCESSOR_REPOS_SUFFIX}")
done

# PROJECT CONFIGS---------------------------------------------------------------#
readonly TARGET_PROJECT_TITLE='Monitor-SoC-DS'
EOF
else
  echo "⚡ The file ${user_config_path} already exists."
fi

# Check if the source_config.sh file already exists, if not, create it with
# default values
if [[ ! -f "${source_config_path}" ]]; then
cat << 'EOF' > "${source_config_path}"
# REPOSITORY CONFIGS------------------------------------------------------------#
SOURCE_REPOS_OWNER='pierzcham'
SOURCE_REPOS=(
  'soc-datascience'
  'soc-datascience-hello'
  'soc-datascience-viz'
  'soc-datascience-wrang'
  'soc-datascience-spatial'
  'soc-datascience-reshape'
  'soc-datascience-paradox'
  'soc-datascience-collabor'
  'soc-datascience-scrap'
  'soc-datascience-bias'
  'soc-datascience-fitting'
  'soc-datascience-nfitting'
  'soc-datascience-valid'
  'soc-datascience-hypo'
  'soc-datascience-wrapup'
  'soc-datascience-project'
)

readonly SOURCE_FILES=(
  'README.md'
  'index.md'
)

# PROJECT CONFIGS---------------------------------------------------------------#
readonly SOURCE_PROJECT_OWNER='pierzcham'
readonly SOURCE_PROJECT_NUMBER='4'
EOF
else
  echo "${WRN} The file ${source_config_path} already exists."
fi

# Check if the system_config.sh file already exists, if not, create it with
# default values
if [[ ! -f "${system_config_path}" ]]; then
cat << 'EOF' > "${system_config_path}"
# [GitHub API docs]: https://docs.github.com/en/rest?apiVersion=2022-11-28
# [GitHub GraphQL docs]: https://docs.github.com/en/graphql/reference

# API HEADERS CONFIGS-----------------------------------------------------------#
readonly GH_API_ACCEPT_HEADER='application/vnd.github+json'
readonly GH_API_VERSION_HEADER='2022-11-28'

# GITHUB CLI CONFIGS------------------------------------------------------------#
readonly GH_CLI_TOKEN_SCOPES=('repo' 'admin:org' 'project')

# ORGANIZATION CONFIGS----------------------------------------------------------#
# [GitHub API docs] The role for the new member.

# admin – Organization owners with full administrative rights to the
# organization and complete access to all repositories and teams.

# direct_member – Non-owner organization members with ability to see other
# members and join teams by invitation.

# billing_manager – Non-owner organization members with ability to manage the
# billing settings of your organization.

# reinstate – The previous role assigned to the invitee before they were removed
# from your organization. Can be one of the roles listed above. Only works if
# the invitee was previously part of your organization.

readonly GH_ORG_ROLE='direct_member'

# [GitHub API docs] Default permission level members have for organization
# repositories. Can be one of: read, write, admin, none. GitHub default: read
readonly GH_ORG_DEFAULT_REPOSITORY_PERMISSION='none'

# [GitHub API docs] Whether organization members can fork private organization
# repositories. GitHub Default: false; the value other than 'false' will be
# treated as 'true'
readonly GH_ORG_MEMBERS_CAN_FORK_PRIVATE_REPOSITORIES=true

# TEAM CONFIGS------------------------------------------------------------------#
# [GitHub API docs] Team privacy settings.
# secret – only visible to organization owners and members of this team.
# closed – visible to all members of this organization.
# GitHub default: secret
readonly GH_TEAM_PRIVACY='closed'

# [GitHub API docs] The permission to grant the team on this repository. We
# accept the following permissions to be set: pull, triage, push, maintain, admin
# and you can also specify a custom repository role name, if the owning
# organization has defined any. If no permission is specified, the team's
# permission attribute will be used to determine what permission to grant the team
# on this repository.
# GitHub default: push
readonly GH_TEAM_REPO_PERMISSION='push'

# [GitHub GraphQL API docs] Notifications settings.
# notifications_enabled – Team members get notified when the team is @mentioned.
# notifications_disabled – no one receives notifications.
# GitHub default: notifications_enabled
readonly GH_TEAM_NOTIFICATIONS='notifications_enabled'

# [GitHub GraphQL API docs] The algorithm to use for review assignment
# LOAD_BALANCE – Balance review load across the entire team.
# ROUND_ROBIN – Alternate reviews between each team member.
readonly GH_TEAM_REVIEW_ASSIGNMENT_ALGORITHM='LOAD_BALANCE'

# [GitHub GraphQL API docs] Notify the entire team of the PR if it is delegated
readonly GH_TEAM_NOTIFY=false

# [GitHub GraphQL API docs] The number of team members randomly selected to
# review the PR
readonly GH_TEAM_MEMBER_COUNT=1

# REPOSITORY CONFIGS------------------------------------------------------------#
# [GitHub API docs] The name of the branch. Cannot contain wildcard characters.
readonly GH_REPO_BRANCH='main'
EOF
else
  echo "${WRN} The file ${system_config_path} already exists."
fi

echo "${YUP} Initialization complete."
}

main() {
  # Check if an argument (init, precheck, open, log, close, reopen or precheck)
  # was provided
  if [[ "$#" -eq 0 ]]; then
    echo -n "${WRN} Usage: gh soc [init|precheck|sync|open|assign|log|close|"
    echo "reopen|delete]"
    exit 1
  fi

  # TODO:
  # Add precheck to every function
  # END:
  
  # Run the appropriate function based on the argument
  case "$1" in
    init)
      init
      ;;
    precheck)
      precheck
      ;;
    sync)
      # Validate global variables before running the sync function
      precheck
      sync
      ;;
    open)
      open
      ;;
    assign)
      # Check if the correct number of non-empty arguments is passed
      if [[ "$#" -ne 2 || -z "$2" ]]; then
	echo "${ERR} Invalid number of arguments or empty argument." >&2
	echo "${WRN} Usage: gh soc assign <repository name>"
	exit 1
      fi
      assign "$2"
      ;;
    log)
      log
      ;;
    close)
      close
      ;;
    reopen)
      reopen
      ;;
    delete)
      delete
      ;;
    *)
      echo -n "${ERR} Invalid argument. Available options: " >&2
      echo "init, precheck, sync, open, assign, log, close, reopen, delete" >&2
      exit 1
      ;;
  esac
}
main "$@"
